// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getNodes: (options: {
	includeKinds?: NodeKind[],
	includeTypes?: string[],
	excludeKinds?: NodeKind[],
	excludeTypes?: string[],
} | null) => typedError<NodeMetadata[], string>(__TAURI_INVOKE("get_nodes", { options })),
	getNodeDetail: (id: string) => typedError<NodeDetail, string>(__TAURI_INVOKE("get_node_detail", { id })),
	getDetailsByIds: (ids: string[]) => typedError<NodeDetail[], string>(__TAURI_INVOKE("get_details_by_ids", { ids })),
	createNode: (payload: CreateNodePayload) => typedError<NodeDetail, string>(__TAURI_INVOKE("create_node", { payload })),
	updateNodeName: (id: string, newName: string) => typedError<null, string>(__TAURI_INVOKE("update_node_name", { id, newName })),
	updateNodeData: (id: string, newData: string) => typedError<null, string>(__TAURI_INVOKE("update_node_data", { id, newData })),
	applyTemplate: (templateId: string, targetId: string) => typedError<NodeDetail, string>(__TAURI_INVOKE("apply_template", { templateId, targetId })),
	getForwardLinks: (sourceNodeId: string) => typedError<NodeMetadata[], string>(__TAURI_INVOKE("get_forward_links", { sourceNodeId })),
	getBacklinks: (targetNodeId: string) => typedError<NodeMetadata[], string>(__TAURI_INVOKE("get_backlinks", { targetNodeId })),
	createLinkWithMetadata: (sourceNodeId: string, targetNodeId: string) => typedError<NodeMetadata, string>(__TAURI_INVOKE("create_link_with_metadata", { sourceNodeId, targetNodeId })),
	getDecks: () => typedError<Deck[], string>(__TAURI_INVOKE("get_decks")),
	getCardsFromDeck: (deckId: string) => typedError<Card[], string>(__TAURI_INVOKE("get_cards_from_deck", { deckId })),
	createDeck: (name: string, parentId: string | null) => typedError<Deck, string>(__TAURI_INVOKE("create_deck", { name, parentId })),
};

/* Types */
export type Card = {
	id: string,
	front: string,
	back: string,
};

export type CreateNodePayload = {
	parent_id: string | null,
	name: string,
	kind: NodeKind,
	type: string,
	data?: string,
	properties: string | null,
};

export type Deck = {
	id: string,
	name: string,
	parentId: string | null,
};

export type IconData = {
	type: string,
	value: string,
};

export type NodeDetail = {
	data: string,
	properties: string,
} & NodeMetadata;

export type NodeFilterOptions = {
	includeKinds?: NodeKind[],
	includeTypes?: string[],
	excludeKinds?: NodeKind[],
	excludeTypes?: string[],
};

export type NodeKind = "folder" | "file" | "template";

export type NodeMetadata = {
	id: string,
	parentId: string | null,
	icon: IconData,
	name: string,
	kind: NodeKind,
	type: string,
	createdAt: string,
	updatedAt: string,
	isTrashed: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

